// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpptestfunc
bool cpptestfunc();
RcppExport SEXP testpkg_cpptestfunc() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(cpptestfunc());
    return __result;
END_RCPP
}
// cpptestwarn
bool cpptestwarn();
RcppExport SEXP testpkg_cpptestwarn() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(cpptestwarn());
    return __result;
END_RCPP
}
